### ISSUE TITLE
Used in anything

### ISSUE THREAD

**Issue by phated** [doowb/koalas#2]
I'm looking for a replacement for _.defaultTo and I stumbled upon this.  Is it used anywhere?  Maybe we can update it and use it in gulp.

**Comment by jonschlinkert** [comment]
Lol @doowb and I have talked about this lib so many times because it was one of the first things he open sourced.

**Comment by doowb** [comment]
Yeah, I'd love to clean this up and use it.

Right now the basic usage is pretty much exactly like `_.defaultTo` except it takes any amount of arguments.

```js
console.log(koalas(undefined, null, 'foo', 'bar');
// 'foo'
```

However, I can see a lot of places where the api can be cleaned up and made more "functional".

**Comment by phated** [comment]
I'd only use it with the single default, but wouldn't mind the API so support variable arguments.  I think it could be implemented similar to https://github.com/substack/defined but checking `undefined`, `null` and `NaN`.

**Comment by phated** [comment]
Or maybe not `NaN`?  I'm not sure I even use that feature

**Comment by doowb** [comment]
Cool... I can add the `NaN` support to work like `defaultTo`...

Also, I've been playing around with it today and I think I can update the api so the above example will work correctly... Right now, you'd have to do either `koalas(a, b).value()` or `koalas.coalesce(a, b)`

**Comment by phated** [comment]
@doowb any progress on this?

**Comment by doowb** [comment]
I've been using it some and I'll try to get the api changes pushed up tonight. Thanks for the reminder.

**Comment by doowb** [comment]
@phated @jonschlinkert  I pushed up changes to the [refactor branch](https://github.com/doowb/koalas/tree/refactor) and did a PR #3

It now exports a method to do a coalesce over a variable amount of arguments and will return the first "valid" value it finds, where "valid" is not undefined, not null, and not NaN.

Let me know if either of you have any feedback.
If you agree with these changes, I'll merge the PR and publish as `1.0.0`.

**Comment by doowb** [comment]
The refactor branch has been merged and published.

**Comment by phated** [comment]
Thanks a ton @doowb!!  This has been swapped into `vinyl-fs` now
